//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompresJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDesign
    {
        public CardDesign()
        {
            this.CardDesignItems = new HashSet<CardDesignItem>();
        }
    
        public int CardDesignID { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<int> OwnImageID { get; set; }
        public Nullable<int> LayoutID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> RecipientID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> MailToMeID { get; set; }
        public Nullable<int> EnvelopeID { get; set; }
        public Nullable<int> PostageID { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<int> AddOnID { get; set; }
        public Nullable<int> OrderLineID { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<System.DateTime> PDFSentDate { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
    
        public virtual ICollection<CardDesignItem> CardDesignItems { get; set; }
    }
}
