//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompresJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.SubCategories = new HashSet<SubCategory>();
        }
    
        public int CategoryID { get; set; }
        public string Category1 { get; set; }
        public string CategoryDescription { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Active { get; set; }
        public Nullable<int> PageID { get; set; }
    
        public virtual ICollection<SubCategory> SubCategories { get; set; }
    }
}
