//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompresJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int OrderID { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> TotalDiscount { get; set; }
        public string Status { get; set; }
        public string TransactionID { get; set; }
        public Nullable<int> AffiliateID { get; set; }
        public string CustomerEMail { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
