//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompresJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLineItem
    {
        public int OrderLineItemID { get; set; }
        public Nullable<int> OrderLineID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public Nullable<double> ItemTotal { get; set; }
    
        public virtual OrderLine OrderLine { get; set; }
    }
}
